modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU LGPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/TheBeefyUpdate/issues"

[[mods]]
modId = "beefyupdate"
version = "${file.jarVersion}"
displayName = "The Beefy Update"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-beefy-update"
logoFile = "logo.png"
credits = "Idea from MMD"
authors = "RonaRage, Nertzhul"
description = '''
Adds fun new beef-related items that have unique effects.'''

[[dependencies.beefyupdate]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beefyupdate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
side = "BOTH"
