modLoader = "javafml"
loaderVersion = "[37,)"
license = "GNU LGPLv3"
issueTrackerURL = "http://github.com/iCrazyBlaze/TheBeefyUpdate"

[[mods]]
modId = "beefyupdate"
version = "${file.jarVersion}"
displayName = "The Beefy Update"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-beefy-update"
logoFile = "logo.png"
credits = "Idea from MMD"
authors = "RonaRage (iCrazyBlaze)"
description = '''
Adds fun new beef-related items that have unique effects.'''

[[dependencies.beefyupdate]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beefyupdate]]
modId="minecraft"
mandatory=true
versionRange="[1.17,1.18)"
side="BOTH"
